import assert from 'node:assert/strict';
import {eraseInk,traceMask} from '../lib/photo-ink.ts';
const stroke={points:[{x:0,y:0},{x:100,y:0}],color:'#000',width:2};
const split=eraseInk([stroke],{x:50,y:0},4);
assert.equal(split.length,2);
assert.equal(split[0].points.at(-1).x,45);
assert.ok(Math.abs(split[1].points[0].x-55)<1e-8);
assert.deepEqual(eraseInk([stroke],{x:50,y:5},4),[stroke]);
assert.deepEqual(eraseInk([stroke],{x:50,y:100},4),[stroke]);
assert.equal(eraseInk([stroke],{x:50,y:0},100).length,0);
assert.deepEqual(stroke.points,[{x:0,y:0},{x:100,y:0}]);
const mask=new Uint8Array(40*20);
for(let y=8;y<12;y++)for(let x=4;x<36;x++)mask[y*40+x]=1;
const paths=traceMask(mask,40,20);
assert.ok(paths.some(path=>path.length>20),'A thick line becomes a connected path, not dots');
for(const path of paths)for(let i=1;i<path.length;i++)assert.ok(Math.hypot(path[i].x-path[i-1].x,path[i].y-path[i-1].y)<=Math.SQRT2+.001);
const ring=new Uint8Array(20*20);
for(let y=4;y<=15;y++)for(let x=4;x<=15;x++)if(x<7||x>12||y<7||y>12)ring[y*20+x]=1;
const loop=traceMask(ring,20,20);
assert.ok(loop.flat().length>20,'Closed letter loops survive tracing');
assert.ok(loop.flat().every(p=>p.x<9||p.x>10||p.y<9||p.y>10),'Letter counters stay empty');
console.log('PASS: partial erase, surviving ends, no-hit, full erase, immutability, connected paths and closed loops');
